# Generated by Django 4.2 on 2023-04-26 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('performer', models.CharField(max_length=150, verbose_name='Исполнитель')),
                ('release_date', models.DateField(verbose_name='Дата выхода')),
            ],
            options={
                'verbose_name': 'Model',
            },
        ),
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Artist',
            },
        ),
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название трека')),
                ('title_alt', models.CharField(max_length=150, verbose_name='Альт. название трека')),
            ],
            options={
                'verbose_name': 'Title',
            },
        ),
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_number', models.IntegerField(verbose_name='Номер трека')),
                ('duration', models.IntegerField(verbose_name='Длительность')),
                ('tempo', models.IntegerField(verbose_name='BPM')),
                ('isrc_code', models.CharField(max_length=12, verbose_name='ISRC')),
                ('explict', models.BooleanField(default=False, verbose_name='Explict')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.albums')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.artists')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.titles')),
            ],
            options={
                'verbose_name': 'Track',
            },
        ),
    ]
