# Generated by Django 4.2 on 2023-04-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albums',
            options={'verbose_name': 'Album'},
        ),
        migrations.AlterField(
            model_name='titles',
            name='title_alt',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Альт. название трека'),
        ),
    ]
