# Generated by Django 4.2 on 2023-04-26 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_albums_options_alter_titles_title_alt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albums',
            name='performer',
        ),
        migrations.AddField(
            model_name='albums',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.artists'),
            preserve_default=False,
        ),
    ]
